#!/bin/bash
export DIRMAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )
source $DIRMAIN/config

#colurs xd
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

mkdir -p $DIRMAIN/ssl

clear

echo -e "T-chat [CLIENT] (type \"help\" for a list of commands)"

while :
do
	echo -e "${GREEN}\u2500\u2500input\u2500\u2500${NC}"
	read -r -e MAIN

	case $MAIN in
		help)
			echo -e "\u2500\u2500list of cmd's\u2500\u2500"
			echo -e "help: this message"
			echo -e "connect: connects you to the server"
			;;
		connect)
			if [[ ! -f "$DIRMAIN/ssl/$HOST.crt" ]];
			then
				echo -e "${RED}[ERROR]${NC} no ssl certificate found"
				echo -e "please copy the server certificate (found on the server your trying to connect to) into the $DIRMAIN/ssl folder and name it $HOST.crt (this changes based on host name)"
			else
				mkdir -p $DIRMAIN/.tmp
				echo -e "connecting..."

				while :
				do
					watch -t -n 1.5 "socat openssl-connect:$HOST:$PORT,cafile=$DIRMAIN/ssl/$HOST.crt - | tail -n $(($LINES - 0))"
					reset > /dev/null 2>&1
					clear

					while :
					do
						read -r -e MSG

						case $MSG in
							!help)
								echo -e "list of msg commands:"
								echo -e "!help = this message"
								echo -e "!exit = exit the chat"
								;;
							!exit)
								exit
								;;
							*)
								date "+%T | %d.%m.%Y" >> $DIRMAIN/.tmp/tmp
								echo -n -e "$NAME: " >> $DIRMAIN/.tmp/tmp
								echo -e "$MSG" >> $DIRMAIN/.tmp/tmp
								echo -e "------------" >> $DIRMAIN/.tmp/tmp
								socat -u FILE:$DIRMAIN/.tmp/tmp openssl-connect:$HOST:$IPORT,cafile=$DIRMAIN/ssl/$HOST.crt
								rm -f $DIRMAIN/.tmp/tmp
								clear
								break
								;;
						esac
					done
				done
			fi
			;;
		*)
			echo -e "unknown user"
			;;
	esac
done
